/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrutasVistas;

import DAOFrutas.DAOfrutas;
import Frutas.ControldeFrutas;
import MenuPrincipal.MenuPrincipal;
import javax.swing.JOptionPane;

/**
 *
 * @author dafer
 */
public class AgregarFrutas extends javax.swing.JFrame {

    public static AgregarFrutas agregarfruta;
    
    /**
     * Creates new form AgregarPokemon
     */
    public AgregarFrutas() {
        initComponents();
    }
public static AgregarFrutas getInstance(){
        if (agregarfruta==null)
agregarfruta=new AgregarFrutas();
    return agregarfruta;
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sexodepokemon = new javax.swing.ButtonGroup();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Direccion = new javax.swing.JPanel();
        TextNombre = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        TextDireccion = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        TexFieNomPok = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        sliEst = new javax.swing.JSlider();
        spiEst = new javax.swing.JSpinner();
        TipoPago = new javax.swing.JPanel();
        Ch_Efectivo = new javax.swing.JCheckBox();
        Ch_Nequi = new javax.swing.JCheckBox();
        Ch_Tarjeta = new javax.swing.JCheckBox();
        Ch_Especie = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        GuardarCompra = new javax.swing.JButton();
        RealizarCompra = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setBackground(new java.awt.Color(102, 255, 102));
        jLabel5.setFont(new java.awt.Font("High Tower Text", 0, 48)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Carrito De Frutas");
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.GridLayout(0, 1));

        Direccion.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre y Apellido"));
        Direccion.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        Direccion.setLayout(new java.awt.GridLayout(1, 0));

        TextNombre.setToolTipText("");
        TextNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextNombreMouseClicked(evt);
            }
        });
        TextNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNombreActionPerformed(evt);
            }
        });
        TextNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextNombreKeyTyped(evt);
            }
        });
        Direccion.add(TextNombre);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Dirección"));
        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        TextDireccion.setToolTipText("");
        TextDireccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextDireccionMouseClicked(evt);
            }
        });
        TextDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextDireccionActionPerformed(evt);
            }
        });
        TextDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextDireccionKeyTyped(evt);
            }
        });
        jPanel6.add(TextDireccion);

        Direccion.add(jPanel6);

        jPanel1.add(Direccion);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Frutas seleccionadas"));
        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        TexFieNomPok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TexFieNomPokMouseClicked(evt);
            }
        });
        jPanel5.add(TexFieNomPok);

        jPanel1.add(jPanel5);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Cantidad"));
        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        sliEst.setMinorTickSpacing(10);
        sliEst.setPaintLabels(true);
        sliEst.setPaintTicks(true);
        sliEst.setSnapToTicks(true);
        sliEst.setToolTipText("0");
        sliEst.setValue(0);
        sliEst.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliEstStateChanged(evt);
            }
        });
        jPanel4.add(sliEst);

        spiEst.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), Float.valueOf(0.0f), Float.valueOf(100.0f), Float.valueOf(1.0f)));
        spiEst.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spiEstStateChanged(evt);
            }
        });
        jPanel4.add(spiEst);

        jPanel1.add(jPanel4);

        TipoPago.setBorder(javax.swing.BorderFactory.createTitledBorder("Formas De Pago"));
        TipoPago.setLayout(new java.awt.GridLayout(0, 2));

        Ch_Efectivo.setText("Efectivo (Pago contra entrega)");
        Ch_Efectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ch_EfectivoActionPerformed(evt);
            }
        });
        TipoPago.add(Ch_Efectivo);

        Ch_Nequi.setText("Nequi");
        TipoPago.add(Ch_Nequi);

        Ch_Tarjeta.setText("Tarjeta");
        TipoPago.add(Ch_Tarjeta);

        Ch_Especie.setText("Especie");
        TipoPago.add(Ch_Especie);

        jPanel1.add(TipoPago);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Codigo De Descuento"));
        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField1);

        jPanel1.add(jPanel3);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel7.setLayout(new java.awt.GridLayout(1, 0));

        GuardarCompra.setText("Guardar Compra");
        GuardarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarCompraActionPerformed(evt);
            }
        });
        jPanel7.add(GuardarCompra);

        RealizarCompra.setText("Realizar Compra");
        RealizarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RealizarCompraActionPerformed(evt);
            }
        });
        jPanel7.add(RealizarCompra);

        jButton2.setText("Regresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton2);

        getContentPane().add(jPanel7, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Ch_EfectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ch_EfectivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ch_EfectivoActionPerformed

    private void TexFieNomPokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TexFieNomPokMouseClicked
        // TODO add your handling code here:
        TextNombre.setText("");
    }//GEN-LAST:event_TexFieNomPokMouseClicked

    private void sliEstStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliEstStateChanged
        // TODO add your handling code here:
        spiEst.setValue(sliEst.getValue());
    }//GEN-LAST:event_sliEstStateChanged

    private void spiEstStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spiEstStateChanged
        // TODO add your handling code here:
        
        sliEst.setValue((int) Float.parseFloat(spiEst.getValue()+""));
        
        
        
    }//GEN-LAST:event_spiEstStateChanged

    private void TextNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextNombreKeyTyped
        // TODO add your handling code here:
        

    }//GEN-LAST:event_TextNombreKeyTyped

    private void TextNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextNombreMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TextNombreMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       MenuPrincipal menuprincipal = MenuPrincipal.getInstance();
        menuprincipal.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void GuardarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarCompraActionPerformed
        // TODO add your handling code here:
        DAOfrutas contFruta= ControldeFrutas.getInstance();
        String DirFru=TextDireccion.getText();
        String NomFru=TextNombre.getText();
        String TipoPago="";
        if(Ch_Efectivo.isSelected())
            TipoPago+="Efectivo ";
        if(Ch_Nequi.isSelected())
            TipoPago+="Nequi ";
        if(Ch_Tarjeta.isSelected())
            TipoPago+="Tarjeta ";
        if(Ch_Especie.isSelected())
            TipoPago+="Especie ";
        String estCan=spiEst.getValue().toString();
         String[] fruta={DirFru,NomFru,TipoPago,estCan};
        if(contFruta.GuardarFruta(fruta)){
           JOptionPane.showMessageDialog(this, "Guardado Exitoso"); 
        }
            
    }//GEN-LAST:event_GuardarCompraActionPerformed

    private void RealizarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RealizarCompraActionPerformed
        // TODO add your handling code here:
        
            DAOfrutas contFruta= ControldeFrutas.getInstance();
        
    }//GEN-LAST:event_RealizarCompraActionPerformed

    private void TextNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNombreActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TextNombreActionPerformed

    private void TextDireccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextDireccionMouseClicked
        // TODO add your handling code here:
        TextDireccion.setText("");
    }//GEN-LAST:event_TextDireccionMouseClicked

    private void TextDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextDireccionActionPerformed

    private void TextDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextDireccionKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TextDireccionKeyTyped

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Ch_Efectivo;
    private javax.swing.JCheckBox Ch_Especie;
    private javax.swing.JCheckBox Ch_Nequi;
    private javax.swing.JCheckBox Ch_Tarjeta;
    private javax.swing.JPanel Direccion;
    private javax.swing.JButton GuardarCompra;
    private javax.swing.JButton RealizarCompra;
    private javax.swing.JTextField TexFieNomPok;
    private javax.swing.JTextField TextDireccion;
    private javax.swing.JTextField TextNombre;
    private javax.swing.JPanel TipoPago;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.ButtonGroup sexodepokemon;
    private javax.swing.JSlider sliEst;
    private javax.swing.JSpinner spiEst;
    // End of variables declaration//GEN-END:variables
}
